### ISSUE TITLE
(New 4.4.3) Textbox | Yes but : no... (是的，但是：不...)

### ISSUE THREAD

**Issue by IdrilK** [MakinoharaShoko/WebGAL#345] opened 2023-08-16 21:43 UTC
Mac OS 13.5, safari 16.6, Webgal terre MAC 4.4.3 ;)
________
Log :
<img width="1440" alt="Capture d’écran 2023-08-16 à 23 25 24" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/3440101c-a660-41cc-bf6a-7180bde2fde4">

TextBox:
<img width="1440" alt="Capture d’écran 2023-08-16 à 23 25 17" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/6d33644b-cc86-47e6-9562-c7e31ca4ce19">

______________________
Log :
<img width="1438" alt="Capture d’écran 2023-08-16 à 23 36 00" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/27192bab-1a80-4354-9ef9-bbe846c554e8">

TextBox :
<img width="1440" alt="Capture d’écran 2023-08-16 à 23 35 53" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/99109032-49c4-436d-aaca-68a69dd26747">

______
OK With 4.4.3.2 :
<img width="1440" alt="Capture d’écran 2023-08-18 à 15 49 12" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/02f8a3f1-cd42-4522-8be8-096b1b8530b4">

**Comment by MakinoharaShoko** [comment] 2023-08-17 01:27
It seems to be an issue with Safari. We have been debugging with Chrome all along, so we didn't really notice this problem. We will now try to fix it

**Comment by MakinoharaShoko** [comment] 2023-08-17 01:29
Yes, I was able to reproduce it on Safari, but since I primarily develop on a Windows computer, I don't have the convenience of installing Safari for debugging purposes. My office computer has Safari, but I can't debug the WebGAL project during work hours. So, I might have to wait until a weekend when I can take my office computer home to debug this issue

**Comment by MakinoharaShoko** [comment] 2023-08-17 01:30
Of course, if there are any developers who use Safari for their daily development and come across this issue, I hope you can assist us in resolving this problem

**Comment by IdrilK** [comment] 2023-08-17 02:04
> Yes, I was able to reproduce it on Safari, but since I primarily develop on a Windows computer, I don't have the convenience of installing Safari for debugging purposes. My office computer has Safari, but I can't debug the WebGAL project during work hours. So, I might have to wait until a weekend when I can take my office computer home to debug this issue

@MakinoharaShoko 
-> Font ok, with ElectronJS, NwJs (so yes, just for safari).
-> space in the name to the box is not show with this version and for all browser.
-> For long text, it's cut  (all browsers). before this version the textbox expand to adjust to a long text (when he can ;))

Ps: take yours time ;).

**Comment by MakinoharaShoko** [comment] 2023-08-17 02:09
Not displaying spaces is indeed a problem, and we will handle it as soon as possible

**Comment by IdrilK** [comment] 2023-08-17 11:07
@MakinoharaShoko 

It would be possible to have CSS functions that don't change part of their name with each compilation: a textbox that becomes textbox_kjdjd09 and then becomes textbox_jfu3j09 and so on ;). This would be more convenient as it takes less time to put everything back in shape :p. I still have a lot of CSS names to fix :D.

<img width="1440" alt="Capture d’écran 2023-08-17 à 13 00 10" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/69843ce3-fff1-4e1c-a93c-6b922c89ca0a">
<img width="1440" alt="Capture d’écran 2023-08-17 à 12 49 54" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/d8012ba0-9bcc-4dd0-afbb-2f969fec1cf0">

**Comment by MakinoharaShoko** [comment] 2023-08-18 01:16
> @MakinoharaShoko
> 
> It would be possible to have CSS functions that don't change part of their name with each compilation: a textbox that becomes textbox_kjdjd09 and then becomes textbox_jfu3j09 and so on ;). This would be more convenient as it takes less time to put everything back in shape :p. I still have a lot of CSS names to fix :D.有可能有一些 CSS 函数在每次编译时不改变它们的一部分名称：一个文本框变成了 textbox_kjdjd09，然后变成了 textbox_jfu3j09，以此类推；）。这样会更方便，因为重新整理所有内容所需的时间更少：p。我还有很多 CSS 名称要修复：D。
> 
> <img alt="Capture d’écran 2023-08-17 à 13 00 10" width="1440" src="https://user-images.githubusercontent.com/103700780/261289909-69843ce3-fff1-4e1c-a93c-6b922c89ca0a.png"> <img alt="Capture d’écran 2023-08-17 à 12 49 54" width="1440" src="https://user-images.githubusercontent.com/103700780/261289979-d8012ba0-9bcc-4dd0-afbb-2f969fec1cf0.png">

Due to the use of CSS Modules, all CSS classes are dynamically generated. If you need to ensure that certain CSS class names do not change, you can consider creating a list explaining why you wish to do so, and future versions can make modifications accordingly

**Comment by IdrilK** [comment] 2023-08-18 02:45
> > @MakinoharaShoko
> 
> Due to the use of CSS Modules, all CSS classes are dynamically generated. If you need to ensure that certain CSS class names do not change, you can consider creating a list explaining why you wish to do so, and future versions can make modifications accordingly



Yes, I had understood the problem. I had fun in the past deconstructing all the CSS, but let's go back to the basics of Webgal  :
- textbox+character_name+buttons, 
- MainMenu(home page)->only for button in Mainpage.
- And Maybe later, in a distant future, a CSS tag if you create a "gal" (gallery) for only characters with more descriptions  (you're not there yet :D.).

No need for the current setting menu, gallery, save etc., everything is very clean (I just adjust the font, font size to make it more variable based on screen sizes and avoid it being too small or too big. ;))

Adding these CSS tags will allow simplifying perhaps  the customizations you are considering in the future ;)

_____
PS: Hehe, I was going to suggest adding generic css tags that won't be touched, ^_^.

**Comment by MakinoharaShoko** [comment] 2023-08-18 02:52
We have received your suggestions and will proceed with the necessary adjustments. In addition, you can directly modify the userStyleSheet.css file in the game directory to load your custom CSS directly into WebGAL. This is the method we support for users to customize style sheets.

**Comment by IdrilK** [comment] 2023-08-18 15:29
-> Font (all browsers) : OK.
-> space in the name (all browsers) : OK.
-> For long text, it's cut (all browsers). before this version the textbox expand to adjust to a long text (when he can...) : NO
-> Css generic static for Textbox : LATER

**Comment by IdrilK** [comment] 2023-08-19 02:42
> 
> . If you need to ensure that certain CSS class names do not change, you can consider creating a list explaining why you wish to do so, and future versions can make modifications accordingly

._Title_buttonList, ._Title_buttonList:Hover, ._Title_button_text, ._Title_button_text_up._Title_button, ._Title_button:hover, ._TextBox_main, ._TextBox_showName, ._TextBox_main, ._Choose_Main, ._Choose_item, ._Choose_item:hover, ._miniAvatarContainer, ._miniAvatarImg, ._miniAvatarImg,

<img width="1440" alt="Capture d’écran 2023-08-19 à 04 21 10" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/6168f3f7-1316-466f-add3-da16e8113cd4">

<img width="1440" alt="Capture d’écran 2023-08-19 à 04 10 15" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/609404ad-ca91-4817-ad65-8a63d93c033d">

<img width="1440" alt="Capture d’écran 2023-08-19 à 04 21 29" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/e7b3c8a2-7587-405a-93ed-d2e86e0bc35a">



And yes I use "userstylesheet" to overwride the css ^_^.

**Closed** 2023-11-12 04:52 UTC
Labels: bug
